### ISSUE TITLE
Add "Fork me on GitHub ribbon"

### ISSUE THREAD

**Issue by dietmarw** [impact/search#17]
I think it would be a good idea to add a "Fork me on GitHub" ribbon.  I found https://github.com/simonwhitaker/github-fork-ribbon-css which makes this rather lightweight and via css only.

I would go for a simple black, bottom right variant.

**Comment by xogeny** [comment]
Where?  Do you want this on the web application itself?  (encouraging people to fork the web application?)  Or do you mean in the detailed listing of each library?

All this presumes that the library **is on GitHub**.  This is again (like #6 and #18) an issue with the index because it must be spelled out very clearly in the index that a) forking is possible and b) how that is done.  The client may be showing results from multiple sources (not necessarily GitHub) so we need to abstract these things out.  The best way to handle that is to include (optional) information in the index.

**Comment by dietmarw** [comment]
I was actually only thinking of the "search" project itself. Because I got questions from people where the source is.

**Comment by xogeny** [comment]
This was added in #24.  However, there is a lingering issue.  On mobile (at least on my iPhone), the ribbon doesn't reach the right margin.

**Comment by xie-dongping** [comment]
I can confirm the issue using an iPhone. However, since I have no Mac, I cannot use debug mode on iOS. 

Rant: So Apple forcing every mobile developer to buy a Mac.

**Comment by dietmarw** [comment]
Tested it with FF developer mode emulating different iPhones and it seems to work as expected. So closing for now.
