### ISSUE TITLE
Only deploy distribution files to impact.github.io

### ISSUE THREAD

**Issue by dietmarw** [impact/search#19]
Currently, impact.github.io contains all kinds of development files from bower. I think only the `dist/*` parts should be sufficient for deployment. Right?

**Comment by xogeny** [comment]
Actually, the `bower_components` directories are actually used.

The issue is this...I'm using `webpack` and, frankly, it is a real pain to deal with jquery and bootstrap in webpack.  There is some issue with fonts in the CSS in bootstrap that cause webpack to have trouble and there are some packages that address this.  But I decided it simply wasn't that important and just avoided bundling jquery and bootstrap with webpack.  That is why the `bower_components` for those packages come through.  But they **are** used by the application.

**Comment by dietmarw** [comment]
OK in that case it's probably fine.
