### ISSUE TITLE
Add a "Back to search results" button on the detailed view

### ISSUE THREAD

**Issue by dietmarw** [impact/search#22]
Currently when one clicks on the library name and gets to the detailed library description then that page is missing a "Back to search results" button. I know that the browsers back button and the impact logo gets you there but people don't expect that anymore. So having a small button with "<- back" or similar would help.

**Comment by xogeny** [comment]
It is not missing, it is simply not advertised.  You can hit the impact logo and it will take you back.  Technically, it isn't a "back" button because it simply takes you to the root.  **But**, the state in the application is preserved which means the original search term is still there.

So the question is...is that sufficient or do we really need to insert an explicit "< Back" button?  BTW, you could easily take a shot at making this change and sending a pull request.  look in `src/lib/Detailed.tsx`.  You'll see the HTML for that page in that file.  You can add a link (same link as the `img` tag, in practice) and then test it by running `make watch`.

**Comment by dietmarw** [comment]
I know that it is not necessary. I'm just saying that the general user nowadays (still) expects this, especially when coming from search results. I'll look into it once time allows.

**Comment by xogeny** [comment]
I think this is resolved in 10cba6b2198a0be5ef566ffe25bf36b87f1e131f
