### ISSUE TITLE
library listed twice

### ISSUE THREAD

**Issue by thorade** [impact/search#31]
Quite some time ago I renamed my library, but when I go to
http://impact.github.io/#/all
it is listed under the old name (HelmholtzFluids) and the new name (HelmholtzMedia).
What is the source of that list?

**Comment by dietmarw** [comment]
Thanks for the report. I need to look at this. Not sure though when this will be.

**Comment by dietmarw** [comment]
OK I've looked into this. The reason is that we list the libraries by their **package** name and not by their repository name. So before version 0.4.0 your library was called HelmholtzFluids and hence it is listed as such (also with the correct versions). One could argue that impact keeps the history (and it has to in case some library depends on the old version). 

Does this explain things?

**Comment by thorade** [comment]
That explains things. So everything is alright and I'll just close this issue.
